remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Feral Sanctity
description: Alchemy in a strange land
show_downloads: false
